#!/usr/bin/env bash
# Configure your Nginx server so that
# redirect_me is redirecting to another page.

apt-get update
apt-get install -y nginx
echo "301 Moved Permanently" > /etc/nginx/html/index.html
echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default
service nginx restart