#!/usr/bin/env bash
# Bash script during your web server project of the custom HTTP header must be X-Served-By
apt-get update
apt-get install -y nginx

SERVER_NAME="$(hostname)"
# i don't have a server 
echo "add_header X-Served-By $SERVER_NAME;" >> /etc/nginx/conf.d/custom_response_header.conf
systemctl restart nginx