#!/usr/bin/env bash
#!/bin/bash

# Install and configure HAProxy on your lb-01 server.
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.*

echo "ENABLED=1" > /etc/default/haproxy


echo "
listen load_balancer
   bind *:80
mode http
balance roundrobin
option httpclose
option forwardfor
server [STUDENT_ID]-web-01 web-01- 3.94.211.46:80 check
server [STUDENT_ID]-web-02 web-02- 100.26.221.221:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
