#!/usr/bin/env bash
# this script show all lists to users 
# this script show all process including those which might not have a TTY
# script that displays a list of currently running processes
ps -a -x -u -f
