#!/usr/bin/env bash
# script that displays a list of currently running processes
# this script show all process including those which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy
ps -a -x -u -f
