#!/usr/bin/env bash
#Write a Bash script that loops from 1 to 10 and
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations

best=1
while [ $best -lt 11 ]
do
	if [ $best = 4 ]
	then
	    echo "bad luck"
	elif [ $best = 8 ]
	then 
	    echo "good luck"
	else 
	    echo "Best School"
	fi
	(( best++ ))
done
